## 1 - Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns

## 2 - Configurações

In [ ]:
# ------------------------------
# Configurações do pandas
# ------------------------------

pd.set_option('display.max_columns', None)              # Mostrar todas as colunas
pd.set_option('display.max_rows', 100)                  # Mostrar mais linhas (opcional)
pd.set_option('display.float_format', '{:.2f}'.format)  # Melhor formatação de float
pd.set_option('display.expand_frame_repr', False)       # Evitar quebra de linha em colunas largas


# ------------------------------
# Configurações visuais
# ------------------------------

# sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

# ------------------------------
# Caminhos
# ------------------------------

DATASET = "rmc.csv"

## 3 - Carregamento dos Dados

In [ ]:
df = pd.read_csv(DATASET)

df.head()

   competenciamov  regiao  uf  municipio sessao  subclasse  saldomovimentacao  cbo2002ocupacao  categoria  graudeinstrucao  idade  horascontratuais  racacor  sexo  tipoempregador  tipoestabelecimento  tipomovimentacao  tipodedeficiencia  indtrabintermitente  indtrabparcial  salario  tamestabjan  indicadoraprendiz  origemdainformacao  competenciadec  indicadordeforadoprazo  unidadesalariocodigo valorsalariofixo regiao_desc  sexo_desc raca_cor_desc      grau_instrucao_desc tipo_movimentacao_desc tipo_estabelecimento_desc tipo_empregador_desc deficiencia_desc aprendiz_desc
0          202512       4  41     410010      Q    8640202                 -1           515215        101                7  28.00             35.00        1     3               0                    1                31                  0                    0               0  1636.25            2                  0                   1          202512                       0                     5          1636,25         Sul   Feminino        Branca    Ensino Médio Completo           Desligamento                      CNPJ                    ?  Sem deficiência  Não Aprendiz
1          202512       4  41     410010      G    4520001                 -1           914405        101                6  18.00             44.00        1     1               0                    1                31                  0                    0               0  1518.00            1                  0                   1          202512                       0                     5          1518,00         Sul  Masculino        Branca  Ensino Médio Incompleto           Desligamento                      CNPJ                    ?  Sem deficiência  Não Aprendiz
2          202512       4  41     410010      P    8599601                 -1           333105        101                9  31.00             40.00        1     1               0                    1                31                  0                    0               0  1724.00            2                  0                   1          202512                       0                     5          1724,00         Sul  Masculino        Branca        Superior Completo           Desligamento                      CNPJ                    ?  Sem deficiência  Não Aprendiz
3          202512       4  41     410010      G    4771701                  1           521130        101                7  85.00              6.00        1     1               0                    1                97                  0                    0               0   210.00            1                  0                   1          202512                       0                     5           210,00         Sul  Masculino        Branca    Ensino Médio Completo               Admissão                      CNPJ                    ?  Sem deficiência  Não Aprendiz
4          202512       4  41     410010      C    3329501                 -1           411005        101                7  21.00             44.00        1     3               0                    1                31                  0                    0               0  1518.00            2                  0                   1          202512                       0                     5          1518,00         Sul   Feminino        Branca    Ensino Médio Completo           Desligamento                      CNPJ                    ?  Sem deficiência  Não Aprendiz

In [ ]:
# Shape
print(f"Linhas: {df.shape[0]}, Colunas: {df.shape[1]}")

# Tipos
df.info()

# Estatísticas
df.describe(include='all').T

Linhas: 106528, Colunas: 37
<class 'pandas.DataFrame'>
RangeIndex: 106528 entries, 0 to 106527
Data columns (total 37 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   competenciamov             106528 non-null  int64
 1   regiao                     106528 non-null  int64
 2   uf                         106528 non-null  int64
 3   municipio                  106528 non-null  int64
 4   sessao                     106528 non-null  str
 5   subclasse                  106528 non-null  int64
 6   saldomovimentacao          106528 non-null  int64
 7   cbo2002ocupacao            106528 non-null  int64
 8   categoria                  106528 non-null  int64
 9   graudeinstrucao            106528 non-null  int64
 10  idade                      106526 non-null  float64
 11  horascontratuais           106528 non-null  float64
 12  racacor                    106528 non-null  int64
 13  sexo                       106528 non-null  int64
 14  tipoempregador             106528 non-null  int64
 15  tipoestabelecimento        106528 non-null  int64
 16  tipomovimentacao           106528 non-null  int64
 17  tipodedeficiencia          106528 non-null  int64
 18  indtrabintermitente        106528 non-null  int64
 19  indtrabparcial             106528 non-null  int64
 20  salario                    106528 non-null  float64
 21  tamestabjan                106528 non-null  int64
 22  indicadoraprendiz          106528 non-null  int64
 23  origemdainformacao         106528 non-null  int64
 24  competenciadec             106528 non-null  int64
 25  indicadordeforadoprazo     106528 non-null  int64
 26  unidadesalariocodigo       106528 non-null  int64
 27  valorsalariofixo           106528 non-null  str
 28  regiao_desc                106528 non-null  str
 29  sexo_desc                  106528 non-null  str
 30  raca_cor_desc              106102 non-null  str
 31  grau_instrucao_desc        105206 non-null  str
 32  tipo_movimentacao_desc     106528 non-null  str
 33  tipo_estabelecimento_desc  106528 non-null  str
 34  tipo_empregador_desc       106528 non-null  str
 35  deficiencia_desc           106497 non-null  str
 36  aprendiz_desc              106528 non-null  str
dtypes: float64(3), int64(23), str(11)
memory usage: 30.1 MB

                              count unique                    top    freq       mean        std       min        25%        50%        75%        max
competenciamov            106528.00    NaN                    NaN     NaN  202512.00       0.00 202512.00  202512.00  202512.00  202512.00  202512.00
regiao                    106528.00    NaN                    NaN     NaN       4.00       0.00      4.00       4.00       4.00       4.00       4.00
uf                        106528.00    NaN                    NaN     NaN      41.00       0.00     41.00      41.00      41.00      41.00      41.00
municipio                 106528.00    NaN                    NaN     NaN  410889.94     629.22 410010.00  410690.00  410690.00  410690.00  412780.00
sessao                       106528     21                      N   34041        NaN        NaN       NaN        NaN        NaN        NaN        NaN
subclasse                 106528.00    NaN                    NaN     NaN 6041022.98 2104750.62 111302.00 4711301.00 5611203.00 8011101.00 9900800.00
saldomovimentacao         106528.00    NaN                    NaN     NaN      -0.18       0.98     -1.00      -1.00      -1.00       1.00       1.00
cbo2002ocupacao           106528.00    NaN                    NaN     NaN  528926.52  175176.34 111220.00  414140.00  514320.00  715230.00  999999.00
categoria                 106528.00    NaN                    NaN     NaN     101.88       5.89    101.00     101.00     101.00     101.00     999.00
graudeinstrucao           106528.00    NaN                    NaN     NaN       7.72       8.20      1.00       7.00       7.00       7.00      80.00
idade                     106526.00    NaN                    NaN     NaN      33.75      11.79     14.00      24.00      32.00      42.00      87.00
horascontratuais          106528.00    NaN                    NaN     NaN      41.87       5.59      0.00      44.00      44.00      44.00      60.00
racacor                   106528.00    NaN                    NaN     NaN       1.78       1.00      1.00       1.00       1.00       3.00       9.00
sexo                      106528.00    NaN                    NaN     NaN       1.95       1.00      1.00       1.00       1.00       3.00       3.00
tipoempregador            106528.00    NaN                    NaN     NaN       0.01       0.11      0.00       0.00       0.00       0.00       2.00
tipoestabelecimento       106528.00    NaN                    NaN     NaN       1.03       0.27      1.00       1.00       1.00       1.00       4.00
tipomovimentacao          106528.00    NaN                    NaN     NaN      62.13      29.74     31.00      40.00      43.00      97.00      98.00
tipodedeficiencia         106528.00    NaN                    NaN     NaN       0.02       0.25      0.00       0.00       0.00       0.00       6.00
indtrabintermitente       106528.00    NaN                    NaN     NaN       0.02       0.16      0.00       0.00       0.00       0.00       9.00
indtrabparcial            106528.00    NaN                    NaN     NaN       0.13       1.06      0.00       0.00       0.00       0.00       9.00
salario                   106528.00    NaN                    NaN     NaN    2479.68    7747.62      0.00    1764.00    2044.26    2400.00 1229200.00
tamestabjan               106528.00    NaN                    NaN     NaN       5.91       2.97      1.00       4.00       6.00       9.00      10.00
indicadoraprendiz         106528.00    NaN                    NaN     NaN       0.02       0.13      0.00       0.00       0.00       0.00       1.00
origemdainformacao        106528.00    NaN                    NaN     NaN       1.00       0.01      1.00       1.00       1.00       1.00       3.00
competenciadec            106528.00    NaN                    NaN     NaN  202512.00       0.00 202512.00  202512.00  202512.00  202512.00  202512.00
indicadordeforadoprazo    106528.00    NaN                    NaN     NaN       0.00       0.00      0.00       0.00       0.00       0.00       0.00
unidadesalariocodigo      106528.00    NaN                    NaN     NaN       4.65       1.60      1.00       5.00       5.00       5.00      99.00
valorsalariofixo             106528  15359                2058,00    5123        NaN        NaN       NaN        NaN        NaN        NaN        NaN
regiao_desc                  106528      1                    Sul  106528        NaN        NaN       NaN        NaN        NaN        NaN        NaN
sexo_desc                    106528      2              Masculino   56072        NaN        NaN       NaN        NaN        NaN        NaN        NaN
raca_cor_desc                106102      6                 Branca   63093        NaN        NaN       NaN        NaN        NaN        NaN        NaN
grau_instrucao_desc          105206     11  Ensino Médio Completo   69528        NaN        NaN       NaN        NaN        NaN        NaN        NaN
tipo_movimentacao_desc       106528      2           Desligamento   63095        NaN        NaN       NaN        NaN        NaN        NaN        NaN
tipo_estabelecimento_desc    106528      3                   CNPJ  105451        NaN        NaN       NaN        NaN        NaN        NaN        NaN
tipo_empregador_desc         106528      3                      ?  106178        NaN        NaN       NaN        NaN        NaN        NaN        NaN
deficiencia_desc             106497      6        Sem deficiência  105755        NaN        NaN       NaN        NaN        NaN        NaN        NaN
aprendiz_desc                106528      2           Não Aprendiz  104649        NaN        NaN       NaN        NaN        NaN        NaN        NaN

In [13]:
# Nulos
nulos = df.isnull().sum().sort_values(ascending=False)
nulos = nulos[nulos > 0]
print(nulos)

grau_instrucao_desc    1322
raca_cor_desc           426
deficiencia_desc         31
idade                     2
dtype: int64

In [11]:
# Duplicatas
df.duplicated().sum()

np.int64(5338)